language: go
go:
  - 1.6.2
sudo: false
install:
  - export CXX="g++-4.8" CC="gcc-4.8" CPP="g++-4.8"
  - go get -v -t ./...
env:
  global:
    - GO15VENDOREXPERIMENT=1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
